function indexModel = importModel(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  INDEXMODEL = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  INDEXMODEL = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  indexModel = importfile1("/Users/Dan/Desktop/Research-WenqiangChen/MATLAB_Files/indexModel.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Mar-2020 14:58:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["StrongestFreqHzX","StrongestFreqHzY","StrongestFreqHzZ", "FingerString"];
opts.VariableTypes = ["double", "double", "double",  "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "FingerString", "EmptyFieldRule", "auto");

% Import the data
indexModel = readtable(filename, opts);

end